@cls
"%NSISDIR%\makensis.exe" /DTYPEVER=blender  /DBLENDERSHORTVER=2.63  "..\src\InstallerScript\KrxImpExp.nsi"
"%NSISDIR%\makensis.exe" /DTYPEVER=blender  /DBLENDERSHORTVER=2.64  "..\src\InstallerScript\KrxImpExp.nsi"
"%NSISDIR%\makensis.exe" /DTYPEVER=blender  /DBLENDERSHORTVER=2.65  "..\src\InstallerScript\KrxImpExp.nsi"
"%NSISDIR%\makensis.exe" /DTYPEVER=blender  /DBLENDERSHORTVER=2.66  "..\src\InstallerScript\KrxImpExp.nsi"
"%NSISDIR%\makensis.exe" /DTYPEVER=blender  /DBLENDERSHORTVER=2.67  "..\src\InstallerScript\KrxImpExp.nsi"
"%NSISDIR%\makensis.exe" /DTYPEVER=blender  /DBLENDERSHORTVER=2.68  "..\src\InstallerScript\KrxImpExp.nsi"
"%NSISDIR%\makensis.exe" /DTYPEVER=blender  /DBLENDERSHORTVER=2.69  "..\src\InstallerScript\KrxImpExp.nsi"
"%NSISDIR%\makensis.exe" /DTYPEVER=blender  /DBLENDERSHORTVER=2.70  "..\src\InstallerScript\KrxImpExp.nsi"
"%NSISDIR%\makensis.exe" /DTYPEVER=blender  /DBLENDERSHORTVER=2.71  "..\src\InstallerScript\KrxImpExp.nsi"
"%NSISDIR%\makensis.exe" /DTYPEVER=blender  /DBLENDERSHORTVER=2.72  "..\src\InstallerScript\KrxImpExp.nsi"
"%NSISDIR%\makensis.exe" /DTYPEVER=blender  /DBLENDERSHORTVER=2.73  "..\src\InstallerScript\KrxImpExp.nsi"
"%NSISDIR%\makensis.exe" /DTYPEVER=blender  /DBLENDERSHORTVER=2.74  "..\src\InstallerScript\KrxImpExp.nsi"
"%NSISDIR%\makensis.exe" /DTYPEVER=blender  /DBLENDERSHORTVER=2.75  "..\src\InstallerScript\KrxImpExp.nsi"
"%NSISDIR%\makensis.exe" /DTYPEVER=blender  /DBLENDERSHORTVER=2.76  "..\src\InstallerScript\KrxImpExp.nsi"
"%NSISDIR%\makensis.exe" /DTYPEVER=blender  /DBLENDERSHORTVER=2.77  "..\src\InstallerScript\KrxImpExp.nsi"
"%NSISDIR%\makensis.exe" /DTYPEVER=blender  /DBLENDERSHORTVER=2.78  "..\src\InstallerScript\KrxImpExp.nsi"
"%NSISDIR%\makensis.exe" /DTYPEVER=blender  /DBLENDERSHORTVER=2.79  "..\src\InstallerScript\KrxImpExp.nsi"
"%NSISDIR%\makensis.exe" /DTYPEVER=blender  /DBLENDERSHORTVER=2.80  "..\src\InstallerScript\KrxImpExp.nsi"
"%NSISDIR%\makensis.exe" /DTYPEVER=blender  /DBLENDERSHORTVER=2.81  "..\src\InstallerScript\KrxImpExp.nsi"
"%NSISDIR%\makensis.exe" /DTYPEVER=blender  /DBLENDERSHORTVER=2.82  "..\src\InstallerScript\KrxImpExp.nsi"
"%NSISDIR%\makensis.exe" /DTYPEVER=blender  /DBLENDERSHORTVER=2.83  "..\src\InstallerScript\KrxImpExp.nsi"
@pause
